<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Livre;

/**
 * PSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Livre $livre
     * @return mixed
     */
    public function getAllThemeQueryBuilder($livre)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $queryBuilder
            ->select('t.id,t.name')
            ->from('AppBundle:Theme', 't')
            ->setParameter('theme', $livre->getId())
         /*   ->setParameter('theme', $partner->getId())
            ->andWhere(
                $queryBuilder->expr()->isNull('p.deleted'))
            ->orderBy('p.name', 'ASC')       */
        ;

       // return $queryBuilder->getQuery()->getResult();
        return $queryBuilder->getQuery()
            ->getResult();
    }
}
