app:
    resource: '@AppBundle/Controller/'
    type: annotation

frontend_livre:
    resource: "@AppBundle/Resources/config/routing/livre.yml"
    prefix:   /livre

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
